retrieve necessary field id

diff --git a/.github/workflows/claim-issue.yml b/.github/workflows/claim-issue.yml
--- a/.github/workflows/claim-issue.yml
+++ b/.github/workflows/claim-issue.yml
@@ -73,6 +73,32 @@ jobs:
           echo "ITEM_ID=$ITEM_ID" >> $GITHUB_ENV
         fi
 
+    - name: Retrieve the project FIELD_ID for "Status"
+      if: env.exact_claim == 'true'
+      id: get_field_id
+      run: |
+        QUERY=$(cat <<EOF
+        {
+          "query": "{ node(id: \\"PVT_kwHOAAMKjM4Ao-Sa\\") { ... on ProjectV2 { fields(first: 10) { nodes { name id } } } } }"
+        }
+        EOF
+        )
+        echo "Sending query: $QUERY"
+
+        RESPONSE=$(curl -X POST -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
+          -H "Content-Type: application/json" \
+          --data "$QUERY" https://api.github.com/graphql)
+
+        echo "GraphQL Response: $RESPONSE"
+        FIELD_ID=$(echo "$RESPONSE" | jq -r '.data.node.fields.nodes[] | select(.name == "Status").id')
+
+        if [ -z "$FIELD_ID" ]; then
+          echo "Error: Could not retrieve FIELD_ID for Status"
+          exit 1
+        else
+          echo "FIELD_ID=$FIELD_ID" >> $GITHUB_ENV
+        fi
+
     - name: Retrieve the "Claimed Tasks" option ID
       if: env.exact_claim == 'true'
       id: find_claimed_tasks_id
@@ -104,7 +130,7 @@ jobs:
       run: |
         QUERY=$(cat <<EOF
         {
-          "query": "mutation { updateProjectV2ItemFieldValue(input: { projectId: \\"PVT_kwHOAAMKjM4Ao-Sa\\", itemId: \\"$ITEM_ID\\", fieldId: \\"FIELD_ID\\", value: { singleSelectOptionId: \\"$CLAIMED_TASKS_ID\\" } }) { projectV2Item { id } } }"
+          "query": "mutation { updateProjectV2ItemFieldValue(input: { projectId: \\"PVT_kwHOAAMKjM4Ao-Sa\\", itemId: \\"$ITEM_ID\\", fieldId: \\"$FIELD_ID\\", value: { singleSelectOptionId: \\"$CLAIMED_TASKS_ID\\" } }) { projectV2Item { id } } }"
         }
         EOF
         )
